version: "3.9"

services:
  jobsearch-app-dev:
    build:
      context: .
      target: dev
    container_name: jobSearch-app-dev-con
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./config/dev.env
      - ./.env
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy   
      mysql_db:                      
        condition: service_healthy   

  mongo:
    image: mongo:latest
    container_name: mongo-con2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:                   
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql_db:
    image: mysql:8.0
    container_name: mysql-con
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    environment:                    
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: "jobSearch"
    healthcheck:                    
      test: ["CMD-SHELL",  "mysqladmin ping -h localhost -uroot -p1111 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  redis:
    image: redis:latest
    container_name: redis-con2
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  redis-data:
  mysql-data:

networks:
  app-network:
    driver: bridge